  excluded:
    - Carthage/

  identifier_name:
    excluded:
    - id
    - x
    - y
    - i
    - vc
    - to
    - vm

  function_body_length:
    warning: 200
    error: 300

  line_length:
    warning: 150
    error: 200
    ignores_urls: true

  type_body_length:
    warning: 300
    error: 400

  cyclomatic_complexity:
    warning: 15
    error: 20

  force_cast: warning
  force_try: warning

  nesting:
    type_level:
      warning: 4
